# Generated by Django 2.1.2 on 2018-10-24 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_pedido_pago'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compra',
            old_name='produto',
            new_name='produto_compra',
        ),
    ]
