# Generated by Django 2.1.2 on 2018-11-08 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_pedido_pago'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item_pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Cliente')),
            ],
        ),
        migrations.RenameField(
            model_name='compra',
            old_name='produto',
            new_name='produto_compra',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='itens',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='valor',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='acrecimos',
        ),
        migrations.AddField(
            model_name='pedido',
            name='funcionario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Funcionario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='produto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Produto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='codigo_pizza',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item_pedido',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Produto'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='item_pedido',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Item_pedido'),
            preserve_default=False,
        ),
    ]
