# Generated by Django 2.1.2 on 2018-11-02 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20181101_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='codigo_pizza',
            field=models.DecimalField(decimal_places=2, max_digits=2),
        ),
    ]
