# Generated by Django 2.1.2 on 2018-11-02 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20181101_2111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='codigo_pizza',
            new_name='acrecimos',
        ),
    ]
