# Generated by Django 2.1.2 on 2018-11-02 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20181101_2223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='acrecimos',
            new_name='cod_pizza',
        ),
    ]
