# Generated by Django 2.1.2 on 2018-11-02 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20181102_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='cod_pizza',
            field=models.CharField(max_length=200),
        ),
    ]
