# Generated by Django 2.1.2 on 2018-11-02 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20181102_0228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='cod_pizza',
            new_name='codigo',
        ),
    ]
