# Generated by Django 2.1.2 on 2018-11-02 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20181102_0236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='codigo',
        ),
        migrations.AddField(
            model_name='produto',
            name='acrescimo',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
