# Generated by Django 2.1.2 on 2018-11-02 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20181102_1400'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='acrescimo',
            new_name='acrecimo',
        ),
    ]
