# Generated by Django 2.1.2 on 2018-11-02 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20181102_1524'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='acrecimo',
            new_name='acrecimos',
        ),
    ]
