# Generated by Django 2.1.2 on 2018-11-02 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20181102_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='acrecimo',
        ),
    ]
