# Generated by Django 2.1.2 on 2018-11-04 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20181103_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_pedido',
            name='quantidade',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
