# Generated by Django 2.1.2 on 2018-11-04 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_item_pedido_pedido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item_pedido',
            name='pedido',
        ),
        migrations.AddField(
            model_name='pedido',
            name='item_pedido',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Item_pedido'),
            preserve_default=False,
        ),
    ]
