# Generated by Django 2.1.2 on 2018-11-04 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20181103_2214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='valor',
        ),
    ]
