# Generated by Django 2.1.2 on 2018-11-04 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20181103_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_pedido',
            name='quantidade',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='item_pedido',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
