# Generated by Django 2.1.2 on 2018-11-04 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20181103_2235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item_pedido',
            name='valor',
        ),
    ]
