# Generated by Django 2.1.2 on 2018-11-04 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_pedido_produto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='produto',
        ),
    ]
