# Generated by Django 2.1.2 on 2018-11-04 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_pedido_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_pedido',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Cliente'),
            preserve_default=False,
        ),
    ]
