# Generated by Django 2.1.2 on 2018-11-04 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_auto_20181104_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_pedido',
            name='quantidade',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
