# Generated by Django 2.1.2 on 2018-11-05 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_auto_20181104_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_pedido',
            name='quantidade',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='produto',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
